# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Remarks dumps

on:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fetch remarks dump
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - run: yarn install
    - run: yarn cli:fetch --ws wss://node.rmrk.app --prefixes=0x726d726b,0x524d524b --append=dumps/latest.json
    - name: Update dump
        uses: test-room-7/action-update-file@v1
        with:
          file-path: dumps/latest.json
          commit-msg: Update remarks dump
          github-token: ${{ secrets.GITHUB_TOKEN }}
